update scripts (colored banner, identify 410 status code, rename functions)

diff --git a/Avgle b/Avgle
--- a/Avgle
+++ b/Avgle
@@ -13,56 +13,50 @@ SUPPORTED_PAGE_TYPE=(avgle xvideos);
 if [[ -t 1 ]]; then # is terminal?
 	COLOR_MODE=`tput colors`;
 	if [[ -n "$COLOR_MODE" ]] && [[ "$COLOR_MODE" -ge 8 ]]; then
-		BOLD="\x1b[1m";
-		RESET="\x1b[0m";
-
-		RED="\x1b[0;31m";
-		RED_BOLD="\x1b[1;31m";
-		YELLOW_BOLD="\x1b[1;33m";
-		GREEN="\x1b[0;32m";
-		GREEN_BOLD="\x1b[1;32m";
-		BLUE="\x1b[0;34m";
-		BLUE_BOLD="\x1b[1;34m";
+		BOLD="\x1b[1m";      DIM="\x1b[2m";           RESET="\x1b[0m";
+		RED="\x1b[0;31m";    RED_BOLD="\x1b[1;31m";
+		YELLOW="\x1b[0;33m"; YELLOW_BOLD="\x1b[1;33m";
+		GREEN="\x1b[0;32m";  GREEN_BOLD="\x1b[1;32m";
+		BLUE="\x1b[0;34m";   BLUE_BOLD="\x1b[1;34m";
+		GREY="\x1b[37m";     CYAN_BOLD="\x1b[1;36m";
 	fi
 fi
 #================================
 #====   Basic functions  ========
 function confirm() {
 	local yn;
-	while true; do read -p "Confirm (y/n) > " yn
-		case $yn in
-			Y|Yes|YES|yes|y) return 0 ;;
-			N|No|NO|no|n) return 1 ;;
-		esac
+	while read -p "Confirm (y/n) > " yn; do
+		if [[ "$yn" == y* ]] || [[ "$yn" == Y* ]]; then return 0; fi
+		if [[ "$yn" == n* ]] || [[ "$yn" == N* ]]; then return 1; fi
 	done
 }
-function title() { echo -e "${BLUE_BOLD}# $1 ${RESET}"; }
+function title() { echo -e "${BLUE_BOLD}# ${1}${RESET}"; }
 function finish() { echo -e "\n${GREEN_BOLD}# Finish!${RESET}\n"; exit 0; }
-function user_abort() { echo -e "\n${YELLOW_BOLD}# Abort by user!${RESET}\n"; exit 0; }
-function warn() { echo -e "${YELLOW_BOLD} warning: ${1} ${RESET}"; }
-function success() { echo -e "${GREEN} success: ${1} ${RESET}"; }
-function error() { echo -e "${RED_BOLD}  error: ${RED}$1${RESET}\n"; exit 1; }
-#================================
+function userAbort() { echo -e "\n${YELLOW_BOLD}# Abort by user!${RESET}\n"; exit 0; }
+function warn() { echo -e "${YELLOW_BOLD}  Warning: ${1} ${RESET}"; }
+function success() { echo -e "${GREEN}  Success: ${1} ${RESET}"; }
+function error() { echo -e "${RED_BOLD}  Error:   ${RED}$1${RESET}\n"; exit 1; }
 
-#===========================================
-#        M a i n   F u n c t i o n
-#===========================================
 
-DIV_LINE="===============================================";
-echo -e "\n${DIV_LINE}"
-echo -e '                    _      '
-echo -e '     /\            | |     '
-echo -e '    /  \__   ____ _| | ___ '
-echo -e '   / /\ \ \ / / _` | |/ _ \'
-echo -e '  / ____ \ V / (_| | |  __/'
-echo -e ' /_/    \_\_/ \__, |_|\___|'
-echo -e '               __/ |       '
-echo -e '              |___/        '
+#=======================================================
+# Banner color palette: #EF413F #FFB938 #3484EE #21A658
+C0="$RESET"; C1="$RED"; C2="$YELLOW"; C3="$BLUE"; C4="$GREEN"; C5="$GREY"
+if [[ -n "$C0" ]]; then
+	if [[ "$COLORTERM" = truecolor ]] || [[ "$COLORTERM" = 24bit ]]; then
+		C1="\x1b[38;2;239;65;63m";   C2="\x1b[38;2;255;185;56m";
+		C3="\x1b[38;2;52;132;238m";  C4="\x1b[38;2;33;166;88m";
+	fi
+fi
+# Print banner
+echo -e '     '$C1'_'$C0'        '$C0'        '$C4'_   '$C1'         '$C0
+echo -e '    '$C1'/ \\'$C2'    __'$C3'  __ _  '$C4'| | '$C1'  ___    '$C0
+echo -e '   '$C1'/ _ \\'$C2'  / /'$C3' / _` | '$C4'| | '$C1' / _ \\  '$C0
+echo -e '  '$C1'/ ___ '$C2'\\/ / '$C3'| (_| | '$C4'| | '$C1'|  __/   '$C0
+echo -e ' '$C1'/_/   '$C2'\\__/  '$C3' \\__, |'$C4' |_|'$C1'  \\___| '$C0
+echo -e '  '$C0'      '$C0'      '$C3'|___/   '$C4'    '$C1'         '$C0
+echo -e "${BOLD} Merge ts files you downloaded from avgle into mp4 via ffmpeg${RESET}"
+echo -e "${DIM} Updated date: 2019-01-30${RESET}"
 echo -e ''
-echo -e '            Update date: 2019-01-26'
-echo -e ''
-echo -e "${BOLD}    Merge ts files you downloaded from avgle into mp4 via ffmpeg${RESET}"
-echo -e "${DIV_LINE}\n"
 
 # ===========================
 # Windows User
@@ -75,7 +69,7 @@ fi
 # ===========================
 # Checking dependencies
 [[ -z `which gawk` ]] && error "\"gawk\" is missing! (Ubuntu: sudo apt install gawk)";
-[[ -z `which sed` ]] && error "\"sed\" is missing! (Ubuntu: sudo apt install sed)";
+# [[ -z `which sed` ]] && error "\"sed\" is missing! (Ubuntu: sudo apt install sed)";
 
 WHICH_FFMPEG="$(which "$FFMPEG_BIN" 2>/dev/null)"
 if [[ -z "$WHICH_FFMPEG" ]]; then
@@ -132,7 +126,7 @@ for _type in "${SUPPORTED_PAGE_TYPE[@]}"; do
 done
 
 [[ -n "$PAGE_TYPE" ]] || error "can't find temporary directory of video ${VIDEO_NAME}";
-pushd "$TEMP_WORKSPACE" || error "goto temp workspace ${TEMP_WORKSPACE} failed!";
+pushd "$TEMP_WORKSPACE" >/dev/null || error "goto temp workspace ${TEMP_WORKSPACE} failed!";
 
 # ===========================
 # Getting max number
@@ -186,14 +180,13 @@ title "Generating list file for ffmpeg ...";
 
 if [[ -e "$LIST_FILE" ]]; then
 	echo -e "\nList file ($LIST_FILE) is existed! Do you want to delete it and continue?";
-	confirm || user_abort;
+	confirm || userAbort;
 	rm -f $LIST_FILE || error "could not delete ${LIST_FILE}";
 fi
 
 echo -e "$FFMPEG_LIST_FILE_CONTENT" > "$LIST_FILE" || error "generate list file failed!";
 # sed -e '/^#/d' -e 's:^http.*mp4/:file :g' "../$M3U8_FILE" > "$LIST_FILE" || error "generate list file failed!";
 
-echo -e "";
 title "Concat file $LIST_FILE generated"
 
 # ===========================
@@ -201,7 +194,7 @@ title "Concat file $LIST_FILE generated"
 title "Converting ts file to mp4 files ..."
 if [[ -e "$TARGET_FILE" ]]; then
 	echo -e "\nTarget file is existed! do you want to delete and continue? ($TARGET_FILE)";
-	confirm || user_abort;
+	confirm || userAbort;
 	rm -f $TARGET_FILE || error "could not delete ${TARGET_FILE}";
 fi
 
@@ -215,7 +208,7 @@ fi
 	|| error "ffmpeg convert response exception!"
 title "Converted ${LIST_FILE} file to ${TARGET_FILE}";
 
-popd || error "got back to parent directory failed!";
+popd >/dev/null || error "got back to parent directory failed!";
 
 # ===========================
 # Deleting files
diff --git a/AvgleDownloader b/AvgleDownloader
--- a/AvgleDownloader
+++ b/AvgleDownloader
@@ -35,105 +35,149 @@ SUPPORTED_PAGE_TYPE=(avgle xvideos);
 if [[ -t 1 ]]; then # is terminal?
 	COLOR_MODE=`tput colors`;
 	if [[ -n "$COLOR_MODE" ]] && [[ "$COLOR_MODE" -ge 8 ]]; then
-		BOLD="\x1b[1m";
-		DIM="\x1b[2m";
-		RESET="\x1b[0m";
-
-		RED="\x1b[0;31m";
-		RED_BOLD="\x1b[1;31m";
-		YELLOW_BOLD="\x1b[1;33m";
-		GREEN="\x1b[0;32m";
-		GREEN_BOLD="\x1b[1;32m";
-		BLUE="\x1b[0;34m";
-		BLUE_BOLD="\x1b[1;34m";
-		CYAN_BOLD="\x1b[1;36m";
-		GREY="\x1b[37m";
+		BOLD="\x1b[1m";      DIM="\x1b[2m";           RESET="\x1b[0m";
+		RED="\x1b[0;31m";    RED_BOLD="\x1b[1;31m";
+		YELLOW="\x1b[0;33m"; YELLOW_BOLD="\x1b[1;33m";
+		GREEN="\x1b[0;32m";  GREEN_BOLD="\x1b[1;32m";
+		BLUE="\x1b[0;34m";   BLUE_BOLD="\x1b[1;34m";
+		GREY="\x1b[37m";     CYAN_BOLD="\x1b[1;36m";
 	fi
 fi
 #================================
 #====   Basic functions  ========
 function confirm() {
 	local yn;
-	while true; do read -p "Confirm (y/n) > " yn
-		case $yn in
-			Y|Yes|YES|yes|y) return 0 ;;
-			N|No|NO|no|n) return 1 ;;
-		esac
+	while read -p "Confirm (y/n) > " yn; do
+		if [[ "$yn" == y* ]] || [[ "$yn" == Y* ]]; then return 0; fi
+		if [[ "$yn" == n* ]] || [[ "$yn" == N* ]]; then return 1; fi
 	done
 }
-function title() { echo -e "${BLUE_BOLD}# $1 ${RESET}"; }
+function title() { echo -e "${BLUE_BOLD}# ${1}${RESET}"; }
 function finish() { echo -e "\n${GREEN_BOLD}# Finish!${RESET}\n"; exit 0; }
-function user_abort() { echo -e "\n${YELLOW_BOLD}# Abort by user!${RESET}\n"; exit 0; }
-function warn() { echo -e "${YELLOW_BOLD} warning: ${1} ${RESET}"; }
-function success() { echo -e "${GREEN} success: ${1} ${RESET}"; }
-function error() { echo -e "${RED_BOLD}  error: ${RED}$1${RESET}\n"; exit 1; }
+function userAbort() { echo -e "\n${YELLOW_BOLD}# Abort by user!${RESET}\n"; exit 0; }
+function warn() { echo -e "${YELLOW_BOLD}  Warning: ${1} ${RESET}"; }
+function success() { echo -e "${GREEN}  Success: ${1} ${RESET}"; }
+function error() { echo -e "${RED_BOLD}  Error:   ${RED}$1${RESET}\n"; exit 1; }
+
+#=======================================
+#=======  Generator functions  =========
+# Generate aria2c download list file by gawk
+# Syntax of download list:
+#   https://aria2.github.io/manual/en/html/aria2c.html#id2
+# Usage:
+#   generateDownloadListForAria2FromStdin <<< "link1 link2 link3 ..."
+#   generateDownloadListForAria2FromStdin "xxx.m3u8" <<< "link1"
+function generateDownloadListForAria2FromStdin() {
+	gawk -vout_name="$1" '{
+		if (NF==1 && out_name) { # only one column and has output filename
+			print $1;
+			print "  out=" out_name;
+		} else {
+			for (i=1;i<=NF;i++) {
+				print $i;
+				out_name = $i;
+				gsub(/^.*\//, "", out_name); # remove prefix of url
+				gsub(/\?.*$/, "", out_name); # remove querystring in url
+				print "  out=" out_name;
+			}
+		}
+	}'
+}
+function generateBetterDownloadQueue() {
+	local MAX_STEP=50;
+	[[ "$DOWNLOADER_TYPE" == aria2c ]] && MAX_STEP=100; # aria2c use multi-threads
+
+	echo -e "$1" | gawk -vMAX_STEP=$MAX_STEP '
+	function printRange() {
+		if(i!=from) print "{" from ".." i "}";
+		else print from;
+	}
+	function resetTo(num) { from = num; i = num; }
+	BEGIN {
+		maxTo = MAX_STEP - 1; # max step is 50: 50-1=49
+		resetTo(-128);
+	}
+	!/^\s*$/ { # ignore empty line
+		if($1 != i + 1) {
+			if(from != -128) printRange();
+			resetTo($1);
+		} else {
+			i = $1;
+			if(i - from == maxTo) {
+				printRange();
+				resetTo(-128);
+			}
+		}
+	}
+	END { if(from >= 0) printRange(); }'
+}
 
 #===================================
 #=======  Network functions  =======
+function cleanDownloadLogOnce() {
+	[[ -n "$__CLEANED_UP_LOG" ]] && return;
+	[[ -f "$DOWNLOAD_LOG" ]] && rm "$DOWNLOAD_LOG";
+}
+function isLastDownload403() {
+	[[ -f "$DOWNLOAD_LOG" ]] && [[ -n "$(grep -e "HTTP/1.1 403 Forbidden" "$DOWNLOAD_LOG")" ]]
+}
+function isLastDownload410() {
+	[[ -f "$DOWNLOAD_LOG" ]] && [[ -n "$(grep -e "HTTP/1.1 410 Gone" "$DOWNLOAD_LOG")" ]]
+}
+function downloadFailed() {
+	local msg="download $1 failed!";
+	if [[ -n "$2" ]]; then msg="${msg} $2";
+	elif [[ -f "$DOWNLOAD_LOG" ]]; then msg="${msg} (log file: $DOWNLOAD_LOG)"; fi
+	error "$msg";
+}
+
 function _download() {
 	# declare `referer` as a local variable, because it should be reset after
 	#    "with_referer" to "no_referer"
-	local referer;
+	local referer ref1 ref2 out1 out2;
 	if [[ "$DOWNLOADER_TYPE" == aria2c ]]; then
-		[[ -f "$DOWNLOAD_LOG" ]] && rm "$DOWNLOAD_LOG";
-
+		cleanDownloadLogOnce;
 		[[ "$1" == with_referer ]] && referer="--referer=$HTTP_REFERER";
 
-		# generate aria2c download list file by gawk
-		# Syntax of download list:
-		# https://aria2.github.io/manual/en/html/aria2c.html#id2
-		gawk -vout_name="$3" '{
-			if (NF==1 && out_name) {
-				print $1;
-				print "  out=" out_name;
-			} else {
-				for (i=1;i<=NF;i++) {
-					print $i;
-					out_name = $i;
-					gsub(/^.*\//, "", out_name);
-					gsub(/\?.*$/, "", out_name);
-					print "  out=" out_name;
-				}
-			}
-		}' <<< "$2" |
+		generateDownloadListForAria2FromStdin "$3" <<< "$2" |
 			"$ARIA2C_BIN" "$referer" --user-agent="$HTTP_USER_AGENT" \
-				--show-files --continue=true \
-				--input-file=- \
-				"$ARIA2C_OPT_J" \
+				--show-files --continue=true --input-file=- "$ARIA2C_OPT_J" \
 				--log="$DOWNLOAD_LOG" --log-level=info;
-	else
-		if [[ "$1" == with_referer ]]; then ref1="--header"; ref2="Referer: $HTTP_REFERER"; fi
-		if [[ -n "$3" ]]; then  out1="-O"; out2="$3"; fi
-		"$WGET_BIN" "$ref1" "$ref2" --header "User-Agent: $HTTP_USER_AGENT" "$out1" "$out2" $2;
+		return $?;
 	fi
+	# wget
+	if [[ "$1" == with_referer ]]; then ref1="--header"; ref2="Referer: $HTTP_REFERER"; fi
+	if [[ -n "$3" ]]; then  out1="-O"; out2="$3"; fi
+	"$WGET_BIN" "$ref1" "$ref2" --header "User-Agent: $HTTP_USER_AGENT" "$out1" "$out2" $2;
 }
 
-# $1: description
-# $2: url
-# $3: [Optional] target file
-function better_wget() {
+# Usage: betterDownloader <description> <urlArray> [targetFile]
+# Example:
+#   betterDownloader "download m3u8 file" "https://xxx.xx/xx.m3u8" "xxx.m3u8"
+#   betterDownloader "download 1..100" "https://xxx.xx/xx-1.ts https://xxx.xx/xx-2.ts ..."
+function betterDownloader() {
 	local download_ok=true;
-
 	if [[ $ENABLE_REFERER == true ]]; then
 		_download with_referer "$2" "$3" || download_ok=false;
 
 		if [[ $download_ok != true ]]; then
-			# has download log but there has no mark of 403, just exit
-			if [[ -f "$DOWNLOAD_LOG" ]] && [[ -z "$(grep -e "HTTP/1.1 403 Forbidden" "$DOWNLOAD_LOG")" ]]; then
-				error "Could not download $1 (log: $DOWNLOAD_LOG)";
+			isLastDownload410 && downloadFailed "$1" "Reason: link is expired!";
+			if [[ -f "$DOWNLOAD_LOG" ]]; then
+				# If download log was generated, but there no traces of 403. then just exit script
+				isLastDownload403 || downloadFailed "$1";
 			fi
-			warn "execute wget with 'Referer' header failed! (trying to execute again without 'Referer' header)";
+			warn "download with 'Referer' header failed! (trying to download again without 'Referer' header)";
 			ENABLE_REFERER=false;
-			_download no_referer "$2" "$3" || error "Could not download $1";
+			_download no_referer "$2" "$3" || downloadFailed "$1";
 		fi
 	else
-		_download no_referer "$2" "$3" || error "Could not download $1 (log: $DOWNLOAD_LOG)";
+		_download no_referer "$2" "$3" || downloadFailed "$1";
 	fi
 }
 
-#===================================
-#=======  Arguments checker functions  =======
-function is_supported_page_type() {
+#==============================================
+#=======  Arguments validate functions  =======
+function isSupportedPageType() {
 	local PAGE_TYPE_OK=false;
 	for _type in "${SUPPORTED_PAGE_TYPE[@]}"; do
 		if [[ $_type == "$PAGE_TYPE" ]]; then
@@ -143,45 +187,44 @@ function is_supported_page_type() {
 	[[ "$PAGE_TYPE_OK" == true ]] && return 0 || return 1;
 }
 
-DIV_LINE="===========================================================";
-echo -e "\n${DIV_LINE}"
-echo -e '     _             _      '
-echo -e '    / \__   ____ _| | ___ '
-echo -e '   / _ \ \ / / _` | |/ _ \'
-echo -e '  / ___ \ V / (_| | |  __/'
-echo -e ' /_/   \_\_/ \__, |_|\___|'
-echo -e '  ____       |___/          _                 _           '
-echo -e ' |  _ \  _____      ___ __ | | ___   __ _  __| | ___ _ __ '
-echo -e ' | | | |/ _ \ \ /\ / / '\''_ \| |/ _ \ / _` |/ _` |/ _ \ '\''__|'
-echo -e ' | |_| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   '
-echo -e ' |____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|   '
-echo -e ''
-echo -e '            Update date: 2019-01-26'
-echo -e ''
+#=======================================================
+# Banner color palette: #EF413F #FFB938 #3484EE #21A658
+C0="$RESET"; C1="$RED"; C2="$YELLOW"; C3="$BLUE"; C4="$GREEN"; C5="$GREY"
+if [[ -n "$C0" ]]; then
+	if [[ "$COLORTERM" = truecolor ]] || [[ "$COLORTERM" = 24bit ]]; then
+		C1="\x1b[38;2;239;65;63m";   C2="\x1b[38;2;255;185;56m";
+		C3="\x1b[38;2;52;132;238m";  C4="\x1b[38;2;33;166;88m";
+	fi
+fi
+# Print banner
+echo -e '     '$C1'_'$C0'        '$C0'        '$C4'_   '$C1'         '$C0
+echo -e '    '$C1'/ \\'$C2'    __'$C3'  __ _  '$C4'| | '$C1'  ___    '$C0
+echo -e '   '$C1'/ _ \\'$C2'  / /'$C3' / _` | '$C4'| | '$C1' / _ \\  '$C0
+echo -e '  '$C1'/ ___ '$C2'\\/ / '$C3'| (_| | '$C4'| | '$C1'|  __/   '$C0
+echo -e ' '$C1'/_/   '$C2'\\__/  '$C3' \\__, |'$C4' |_|'$C1'  \\___| '$C5'  Downloader'$C0
+echo -e '  '$C0'      '$C0'      '$C3'|___/   '$C4'    '$C1'         '$C0
 echo -e "${BOLD} ${USAGE}${RESET}"
+echo -e "${DIM} Updated date: 2019-01-30${RESET}"
 echo -e ''
-echo -e "${DIV_LINE}\n"
 
-# ===========================
-# Windows User
+# ==============================
+# Detect Windows user (Git Bash)
 WIN_USER=false
 UNAME_S="$(uname -s)";
-if [[ "$UNAME_S" == MINGW* ]] || [[ "$UNAME_S" == CYGWIN* ]]; then
-	WIN_USER=true;
-fi
+if [[ "$UNAME_S" == MINGW* ]] || [[ "$UNAME_S" == CYGWIN* ]]; then WIN_USER=true; fi
 
-# ===========================
+# =============================
 # 1. Checking dependencies
 # 2. Searching and binding downloader: wget or aria2c
 
 # Find a executable binary file
-# Usage:  search_exec_file <exec_name> [required] [package-name]
-exec_file_result=""
-function search_exec_file() {
+# Usage:  searchExec <exec_name> [required] [package-name]
+searchExecResult=""
+function searchExec() {
 	local SCRIPT_DIR FIND_RESULT;
 
-	exec_file_result="$(which "$1" 2>/dev/null)";
-	[[ -n "$exec_file_result" ]] && return 0;
+	searchExecResult="$(which "$1" 2>/dev/null)";
+	[[ -n "$searchExecResult" ]] && return 0;
 
 	if [[ $WIN_USER == true ]]; then
 		SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)";
@@ -196,7 +239,7 @@ function search_exec_file() {
 				return 1;
 			fi
 		fi
-		exec_file_result="${SCRIPT_DIR}/${FIND_RESULT}";
+		searchExecResult="${SCRIPT_DIR}/${FIND_RESULT}";
 		popd > /dev/null;
 		return 0;
 	fi
@@ -206,21 +249,21 @@ function search_exec_file() {
 		return 1;
 	fi
 }
-function bind_downloader() {
-	if search_exec_file "$ARIA2C_BIN" optional; then
-		ARIA2C_BIN="$exec_file_result";
+function resolveDownloader() {
+	if searchExec "$ARIA2C_BIN" optional; then
+		ARIA2C_BIN="$searchExecResult";
 		DOWNLOADER_TYPE="aria2c";
 		echo -e "${CYAN_BOLD}🚀  aria2 mode is enabled! 🚀${RESET}"
 
-	elif search_exec_file "$WGET_BIN" required "$WGET_BIN"; then
-		WGET_BIN="$exec_file_result";
+	elif searchExec "$WGET_BIN" required "$WGET_BIN"; then
+		WGET_BIN="$searchExecResult";
 		DOWNLOADER_TYPE="wget";
 
 	fi
 }
 
 [[ -z `which gawk` ]] && error "\"gawk\" is missing! (Ubuntu: sudo apt install gawk)";
-bind_downloader;
+resolveDownloader;
 
 # ===========================
 # Checking arguments
@@ -244,7 +287,7 @@ done
 
 [[ -z "$VIDEO_NAME" ]] && error "option \"name\" is missing!";
 [[ -z "$M3U8_URL_BASE64" ]] && error "option \"url\" is missing!";
-is_supported_page_type "$PAGE_TYPE" || error "invalid type: \"${PAGE_TYPE}\" ";
+isSupportedPageType "$PAGE_TYPE" || error "invalid type: \"${PAGE_TYPE}\" ";
 
 echo -e "${GREY}Video name:${DIM} ${VIDEO_NAME}${RESET}";
 echo -e "${GREY}Base64 of m3u8 URL:${DIM} ${M3U8_URL_BASE64}${RESET}";
@@ -285,7 +328,7 @@ if [[ ! -f "${M3U8_FILE}" ]]; then
 	OLD_DOWNLOAD_LOG="${DOWNLOAD_LOG}";
 	DOWNLOAD_LOG="${TEMP_WORKSPACE}/${OLD_DOWNLOAD_LOG}";
 
-	better_wget 'm3u8 file' "$M3U8_URL" "$DOWNLOAD_TARGET_FILE";
+	betterDownloader 'm3u8 file' "$M3U8_URL" "$DOWNLOAD_TARGET_FILE";
 	success "downloaded m3u8 file to \"$DOWNLOAD_TARGET_FILE\"";
 
 	# restore log location
@@ -366,43 +409,14 @@ if [[ "$MISSING_FILE_COUNT" == "0" ]]; then
 	finish;
 fi
 
-function get_better_file_list() {
-	MAX_STEP=50;
-	[[ "$DOWNLOADER_TYPE" == aria2c ]] && MAX_STEP=100; # aria2c use multi-threads
-
-	echo -e "$1" | gawk -vMAX_STEP=$MAX_STEP '
-	function printRange() {
-		if(i!=from) print "{" from ".." i "}";
-		else print from;
-	}
-	function resetTo(num) { from = num; i = num; }
-	BEGIN {
-		maxTo = MAX_STEP - 1; # max step is 50: 50-1=49
-		resetTo(-128);
-	}
-	!/^\s*$/ { # ignore empty line
-		if($1 != i + 1) {
-			if(from != -128) printRange();
-			resetTo($1);
-		} else {
-			i = $1;
-			if(i - from == maxTo) {
-				printRange();
-				resetTo(-128);
-			}
-		}
-	}
-	END { if(from >= 0) printRange(); }'
-}
-get_better_file_list "$MISSING_FILE" | while read range; do
-
+generateBetterDownloadQueue "$MISSING_FILE" | while read range; do
 	P0="${DOWNLOAD_URL_PREFIX}/${FILE_NAME_PREFIX}";
 	P1="${FILE_NAME_SUFFIX}${DOWNLOAD_URL_SUFFIX}";
 	DOWNLOAD_URL="$(eval "echo $range" |
 		gawk -vp0="$P0" -vp1="$P1" '{for(i=1;i<=NF;i++)printf("%s ",p0 $i p1);}')";
 
 	title "downloading ${range}/${LAST_FRAGMENT_ID} ...";
-	better_wget "\"${FILE_NAME_PREFIX}${range}${FILE_NAME_SUFFIX}\", please try again!" "$DOWNLOAD_URL";
+	betterDownloader "\"${FILE_NAME_PREFIX}${range}${FILE_NAME_SUFFIX}\", please try again!" "$DOWNLOAD_URL";
 	success "progress ${range}/${LAST_FRAGMENT_ID}";
 
 done || exit 1;
